#!/bin/sh

echo "Do you want to synchronise changes? [y/n]"
read changes
if [[ $changes == "y" ]]; then
  su -c - pascal HOME=/home/pascal; unison unison && unison all
fi

urxvtc -e newsbeuter
urxvtc -e hsgtd
