#!/bin/sh

# Work around issue NixOS/nixpkgs#119513
if [ -z "$_XPROFILE_SOURCED" ]; then
  export _XPROFILE_SOURCED=1

# GnuPG-Agent
export SSH_AUTH_SOCK
SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent

# Start notification daemon
dunst &

# Disable beep
xset b off &

# Set DPMS off
xset -dpms &

# Load the xbindkeys configuration
xbindkeys -f $HOME/.xbindkeysrc &

# Vertical and horizontal scrolling on Thinkpads
xinput set-int-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation" 8 1
xinput set-int-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Button" 8 2
xinput set-int-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Axes" 8 6 7 4 5

# Start trayer
trayer --edge top \
       --align right \
       --SetDockType true \
       --SetPartialStrut true \
       --expand true \
       --width 10 \
       --widthtype percent \
       --transparent true \
       --alpha 0 \
       --tint 0x000000 \
       --height 18 &

# Start nm-applet
nm-applet &

# Configure the wallpaper
"$HOME"/bin/wallpaper-config &

# Set background / wallpaper
"$HOME"/bin/wallpaper &

# Autostart applications
"$HOME"/bin/x-autostart &

xmodmap "$HOME"/.Xmodmap

fi