#!/bin/sh

# Work around issue NixOS/nixpkgs#119513
if [ -z "$_XPROFILE_SOURCED" ]; then
  export _XPROFILE_SOURCED=1

# Keyring SSH Support
eval $(/run/wrappers/bin/gnome-keyring-daemon --start --daemonize)
export SSH_AUTH_SOCK

# Start notification daemon
dunst &

# Disable beep
xset b off &

# Set DPMS off
xset -dpms &

# Load the xbindkeys configuration
xbindkeys -f $HOME/.xbindkeysrc &

# Vertical and horizontal scrolling on Thinkpads
xinput set-int-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation" 8 1
xinput set-int-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Button" 8 2
xinput set-int-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Axes" 8 6 7 4 5

# Start stalonetray
stalonetray &

# Start nm-applet
nm-applet &

# Configure the wallpaper
"$HOME"/bin/wallpaper-config &

# Set background / wallpaper
"$HOME"/bin/wallpaper &

# Autostart applications
"$HOME"/bin/x-autostart &

xmodmap "$HOME"/.Xmodmap

fi
