#!/bin/sh

# The Backup intervals in use.
# Must be a subset of the intervals
# defined in the rsnapshot config
intervals=(weekly)

# Prompts the user to run the backup
# for the given interval.
createBackup(){
echo -n "Create a $1 backup NOW? [yn] "

while [ 1 ]
do
    read answer
    case $answer in
        "n" )
            return 0
            ;;
        "y" )
            echo -n "Which device contains the encrypted backup volume? [std. sdb1] "
            read device
            echo -n "Enter root "; suc "
            cryptsetup luksOpen /dev/${device:-sdb1} backup &&
            mount /dev/mapper/backup/ /backup &&
            rsnapshot $1 &&
            umount /backup &&
            cryptsetup luksClose backup" &&
            rm ~/.$1-backup
            return 0 ;;
        * )
            echo -n "Invalid input! Try again: "
            ;;
    esac
done
}

# The user is prompted to run a backup
# if and only if a file .$interval-backup
# exists in his $HOME (e.g created by
# a cronjob). Where $interval ∈ intervals.
# This file will be removed, if the backup
# was successful.

# Example cronjobs:
# @daily ID=daily-backup /bin/touch /home/user/.daily-backup
# @weekly ID=weekly-backup /bin/touch /home/user/.weekly-backup
for interval in ${intervals[@]}
do
  if [ -f ~/.$interval-backup ]; then
      createBackup "$interval"
  fi
done
