#!/bin/sh

# Auxiliarity function
function unison_sync() {
    # It's important to sync the unison profile
    # files first
    unison unison && unison all
    if [ $? -ne 0 ]; then
        exit 1
    fi
}

function sshkey_is_added() {
    [[ ! $(ssh-add -l) = *$HOME/.ssh/id_rsa* ]]
}

echo -n "Do you want to synchronise changes? [y/o/n/d] "

while [ 1 ]
do
    read action
    case $action in
        
        # Sync all changes and start depending programs
        "y" )
            if sshkey_is_added; then
                ssh-add && unison_sync
            else
                unison_sync
            fi
            break
            ;;
        
        # Don't sync and start depending programs
        "n" )
            break
            ;;

        # Only add the ssh key
        "o" )
            if sshkey_is_added; then
                ssh-add
            fi
            exit 0
            ;;
        
        # Don't sync and don't start programs
        "d" )
            exit 0
            ;;

        * )
            echo -n "Invalid input! Try again: "
            ;;
    esac
done

unset -f unison_sync
unset -f sshkey_is_added

# Add programms to start after successful synchronisation.
# Most likely programs that depends on data that was synced.
urxvtc -e newsbeuter
urxvtc -e hsgtd
