#!/bin/sh

echo -n "Do you want to synchronise changes? [y/n/d] "
read action
case "$action" in
    y)
      HOME=/home/pascal
      ssh-add && (connected1=$(unison unison)) && (connected2=$(unison all))
      if [[ $connected1=*"Could not resolve hostname"* ||
            $connected2=*"Could not resolve hostname"* ]]; then
          exit 1
      fi
    ;;
    d)
      exit 0
    ;;
esac

# Add programms to start
# after successful synchronisation
urxvtc -e newsbeuter
urxvtc -e hsgtd
