#!/bin/sh

# Auxiliarity function
function unison_sync() {
    # It's important to sync the unison profile
    # files first without deletions, that allows
    # correct handling of the deletion of subconfigs.
    #
    # $HOME is the local root of unison.
    unison unison -nodeletion $HOME && unison all && unison unison
    if [ $? -ne 0 ]; then
        exit 1
    fi
}

echo -n "Do you want to synchronise changes? [y/n/d] "

while [ 1 ]
do
    read action
    case $action in

        # Sync all changes and start depending programs
        "y" )
            unison_sync
            break
            ;;

        # Don't sync and start depending programs
        "n" )
            break
            ;;

        # Don't sync and don't start programs
        "d" )
            exit 0
            ;;

        * )
            echo -n "Invalid input! Try again: "
            ;;
    esac
done

unset -f unison_sync

# Add programms to start after successful synchronisation.
# Most likely programs that depends on data that was synced.
urxvtc -e hsgtd &!
$HOME/.bin/org-agenda &!
