#!/bin/sh

# Url and cookie have to be provided as parameters to
# this script (e.g. by jumanji).
url=$1
cookie=$2

# File to save $last
last_path=$HOME/.download-helper

# Get last directory downloaded to
last=$(cat $last_path)

# Include the dmenu config
. $HOME/configs/dmenu_config.sh

# Prompt the user for the filename and propagate the return code
function runDmenu() {
  file=$((echo -e ".\n.."; ls; echo -e "!open\n!last (${last})") | dmenu $dmenu_conf -l 15 -p $PWD)
  return $(test -n "$file")
}

# A simple abstraction from curl
# first parameter: the cookie
# second parameter: the url
# third parameter: the local filename
# FIXME: Certificate support
function runCurl() {
  if [ $# -eq 2 ]; then
    curl -kL --cookie-jar ${1} ${2} -O
  else
    curl -kL --cookie-jar ${1} ${2} -o ${3}
  fi
  echo $PWD > $last_path
}

# Run until location is choosen or dmenu exists
while runDmenu; do

  # Changes to last directory
  if [[ $file = "!last"* ]]; then
      cd $last

  # Opens the file directly with an application selected by dmenu
  elif [ $file = "!open" ]; then
      cmd=$(dmenu_path | dmenu $dmenu_conf)
      tempfile=$(mktemp)
      runCurl $cookie $url $tempfile && exec $cmd $tempfile

  # File will be downloaded with original name
  elif [ $file = "." ]; then
      runCurl $cookie $url
      exit

  # Change directory
  elif [ -d $file ]; then
      cd $file

  # Overwrite existing file
  elif [ -f $file ]; then
      ans=$(echo -e "Yes\nNo" | dmenu $dmenu_conf -i -p "Overwrite existing file $file?")
      if echo $ans | grep -i "^Yes" > /dev/null ; then
        runCurl $cookie $url $PWD/$file
      fi
      exit

  # Create new file
  else
      runCurl $cookie $url $PWD/$file
      exit
  fi
done
