#!/bin/sh

url=$1
cookie=$2

# File to save $last
last_file=$HOME/.filechooser

# Get last directory downloaded to
last=$(cat $last_file)

. $HOME/configs/dmenu_config.sh

function runDmenu() {
  file=$((echo -e ".\n.."; ls; echo "!open"; echo "!last (${last})") | dmenu $dmenu_conf -l 15 -p $PWD)
  return $(test -n "$file")
}

# FIXME: Certificate support
function runCurl() {
  if [ $# -eq 2 ]; then
    curl -kL --cookie-jar ${1} ${2} -O
  else
    curl -kL --cookie-jar ${1} ${2} -o ${3}
  fi
  echo $PWD > $last_file
}

# Run until location is choosen, or dmenu exists
while runDmenu; do

  # Changes to last directory
  if [[ $file = "!last"* ]]; then
      cd $last

  # Opens the file directly with an application selected by dmenu
  elif [ $file = "!open" ]; then
      cmd=$(dmenu_path | dmenu $dmenu_conf)
      tempfile=$(mktemp)
      runCurl $cookie $url $tempfile && exec $cmd $tempfile

  # File will be downloaded with original name
  elif [ $file = "." ]; then
      runCurl $cookie $url
      exit

  # Change directory
  elif [ -d $file ]; then
      cd $file

  # Overwrite existing file
  elif [ -f $file ]; then
      ans=$(echo -e "Yes\nNo" | dmenu $dmenu_conf -i -p "Overwrite existing file $file?")
      if echo $ans | grep -i "^Yes" > /dev/null ; then
        runCurl $cookie $url $PWD/$file
      fi
      exit

  # Create new file
  else
      runCurl $cookie $url $PWD/$file
      exit
  fi
done
