#!/bin/sh

url=$1
cookie=$2

. $HOME/configs/dmenu_config.sh

function runDmenu() {
  file=$((echo ".."; ls) | dmenu $dmenu_conf -l 15 -p $PWD)
  return $(test -n "$file")
}

# FIXME: Certificate support
function runCurl() {
  curl -k --cookie-jar $3 "${1}" -o "${2}"
}

while runDmenu; do
  if [ -d $file ]; then
      cd $file
  elif [ -f $file ]; then
      ans=$(echo -e "Yes\nNo" | dmenu $dmenu_conf -i -p "Overwrite existing file $file?")
      if echo $ans | grep -i "^Yes" > /dev/null ; then
        runCurl $url $PWD/$file $cookie
      fi
      exit
  else
      runCurl $url $PWD/$file $cookie
      exit
  fi
done
