#!/bin/sh

if [[ $# -ne 1 ]]; then
    echo "Warning: No username"
    exit 1
fi

echo -n "Password: "

stty -echo
read password
stty echo
echo ""

output=$(wget --no-check-certificate -qO- --http-user=$1 --http-passwd=${password} "https://printer.rbg.informatik.tu-darmstadt.de/quota")

if [[ $output == *"you don't have any printquota yet"* ]]; then
    echo "Warning: You don't have any printquota yet, it will be
    created when you print the first time"
    exit 1
fi

if [[ $output == ""  ]]; then
    echo "Warning: Wrong password or username"
    exit 1
fi

var=$(echo $output | grep -o "<strong>[0-9]*[0-9]</strong>" | grep -o "[0-9]*[0-9]")
total=$(echo "${var}" | head -n1)
used=$(echo "${var}" | tail -n1)

echo "Available quota: $((${total}-${used}))"
echo "Used quota: ${used}"
echo "Total quota: ${total}"
