#!/bin/sh

case $(hostname) in
  'firmin')
      synclient TapButton1=0
      synclient TapButton2=0
      synclient TapButton3=0
      synclient VertEdgeScroll=1
      ;;
   'subiectiva')
      synclient TouchpadOff=1
      ;;
esac
