#!/bin/sh
# This script is started form .xinitrc and provides
# a host specific synclient configuration.

case $(hostname) in
  'firmin' | 'brauchli')
      synclient TapButton1=0
      synclient TapButton2=0
      synclient TapButton3=0
      synclient VertEdgeScroll=1
      ;;
   'subiectiva')
      synclient TouchpadOff=1
      ;;
esac
