#!/bin/sh


# The unison profiles that shall be synchronized.
PROFILES=(
        config
        docs
        org
        projects
        studium
        wallpapers
        web
        )

# The name and path of the temporary unison profile.
TMP_NAME=tmp
TMP_PROFILE=$HOME/.unison/$TMP_NAME.prf

# The profile the synchronize the unison profiles
UNISON_PRF=unison

# The default profile. This profile must contain the roots.
DEFAULT_PRF=default

# The local root defined in the default profile.
LOCAL_ROOT=$HOME

# Clean up on termination
trap "rm ${TMP_PROFILE}" SIGINT SIGTERM SIGQUIT SIGKILL EXIT

# If arguments are given PROFILES is ignored
# and the arguments are used as profiles.
if [ ! -z $1 ]; then
   PROFILES=()
   PROFILES=$@
fi

# The internal profile TMP_NAME is removed to
# prevent infinite loops.
PROFILES=${PROFILES[@]//$TMP_NAME/}

# Abort if only the internal profile shall be synchronized.
if [ "${PROFILES}" = "" ]; then
    echo "Attempting to only synchronize the internal"\
         "profile ${TMP_NAME}. Aborting..."
    exit 1
fi

# Create the temporary unison profile.
echo "include ${DEFAULT_PRF}" > $TMP_PROFILE
for PROFILE in ${PROFILES[@]}; do
    echo "include ${PROFILE}" >> $TMP_PROFILE
done

echo "Synchronizing the following profiles: ${PROFILES[@]}"

# It is important to synchronize the UNISON_PRF profile
# first without deletions at the local root, that allows the
# correct deletion of remaining files in profiles included
# in TMP_NAME.
unison $UNISON_PRF -nodeletion $LOCAL_ROOT -ignore "Name ${TMP_NAME}.prf" &&
unison $TMP_NAME &&
unison $UNISON_PRF -ignore "Name ${TMP_NAME}.prf"
if [ $? -ne 0 ]; then
    exit 1
fi
