#!/bin/sh

# Path to background images
BGPATH=$HOME/wallpapers/

# Path to file with active backgrounds
# one line per background
BGACTIVE=$BGPATH/current

# Adds first parameter as prefix to the lines of the second parameter
# therefore the second parameter must bei a file
addprefix(){
  for s in $(cat $2)
  do
    echo -n $1$s" "
  done
}

# Set wallpaper
setWallpaper(){
  bgs $(addprefix $BGPATH $BGACTIVE)
}

# Set initial wallpaper
setWallpaper

# Look for wallpaper changes and apply them
while inotifywait $BGACTIVE; do
  setWallpaper
done
