#!/bin/sh
# This script is startet from .xinitrc and provides
# a host specific autostart

urxvtc -e $HOME/.bin/checkforsync &
emacs --daemon &
case $(hostname) in
  'firmin')
      ;;
  'subiectiva')
      thunderbird &
      firefox &
      ;;
esac
